source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'

target 'ZFPlayer_Example' do
    pod 'FDFullscreenPopGesture'
    pod 'MJRefresh'
    pod 'ZFPlayer', :path => '../'
    pod 'ZFPlayer/ControlView', :path => '../'
    pod 'ZFPlayer/AVPlayer', :path => '../'
    pod 'ZFPlayer/ijkplayer', :path => '../'

    pod 'IJKMediaFramework'
end
